name: tok
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip
  - pip:
    - accelerate==0.33.0
    - albumentations==0.4.3
    - diffusers==0.30.0
    - transformers==4.41.2
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - numpy==1.24.4
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - torch==2.2.2
    - torch-fidelity==0.3.0
    - torch-summary==1.4.5
    - torchaudio==2.2.2
    - torchmetrics==0.6.0
    - torchstat==0.0.7
    - torchvision==0.17.2
    - wandb==0.17.0
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.7.0
    - einops-exts==0.0.4