model:
  codebook_dim: 64
  encoder_ch_mult: [1, 1, 2, 2, 4]
  decoder_ch_mult: [1, 1, 2, 2, 4]
  bernoulli: true
  use_negative: false
  z_channels: 256
  dropout_p: 0.0
  matryoshka: true
  

train:
  ae_resume_path: 'ckpts/a800/vqvae-matryoshka_64-170k'
  loss_resume_path: 'experiment/matryoshka_64_newdec/loss-matryoshka_64_newdec-62k'
  global_step: 1
  exp_name: &exp_name 'matryoshka_entropy'
  wandb_proj: *exp_name
  output_dir: *exp_name
  logging_dir: 'logs'
  mixed_precision: 'bf16'
  gradient_accumulation_steps: 4
  report_to: 'wandb'
  num_iters: 200000
  val_every: 100
  save_every: 1000
  disc_start: 1
  disc_weight: 0.05

data:
  path: '/data/Largedata/ImageNet_wds/imagenet-train-{000000..001281}.tar'
  batch_size: 8