model:
  codebook_dim: 64
  encoder_ch_mult: [1, 1, 2, 2, 4]
  decoder_ch_mult: [1, 1, 2, 2, 4]
  bernoulli: true
  use_negative: false
  z_channels: 256
  dropout_p: 0.0
  matryoshka: true
  

train:
  ae_resume_path: 'experiment/matryoshka_64/vqvae-matryoshka_64-170k'
  loss_resume_path: 'experiment/matryoshka_64/loss-matryoshka_64-170k'
  global_step: 1
  exp_name: &exp_name 'new_dvd_0.8decay_0.5inter_0.1entropy'
  wandb_proj: *exp_name
  output_dir: *exp_name
  logging_dir: 'logs'
  mixed_precision: 'no'
  gradient_accumulation_steps: 2
  report_to: 'wandb'
  num_iters: 300000
  val_every: 1000
  save_every: 1000
  disc_start: 1
  disc_weight: 0.03

data:
  path: '/data/ImageNet/imagenet-train-{000000..001281}.tar'
  batch_size: 30